### ISSUE TITLE
Adding notes in the Mobile interface doesn't work

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkManager#1037]
Check if the button Save is linked to any WebService.
see Issue #1062.

**Comment by damirius** [comment]
@WebDevJL @bsaiken 

This should be fixed, I'm working on adding photos to the notes so you can test it together with that if you wish later.

**Comment by bsaiken** [comment]
@damirius 
This is now working, and the notes are appearing on `/activetask/showForm`.
