### ISSUE TITLE
Task UI bugs

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkManager#1055]
- test 20: all tooltips are missing except the technicians, locations and task info
- test 24: #765 
- test 29: does the issue exist?
- test 30: no sorting done
- test 32: data collection and Services checkbox don't display properly in edit mode

**Comment by bsaiken** [comment]
> test 32: data collection and Services checkbox don't display properly in edit mode

This has been fixed.

**Comment by bsaiken** [comment]
Both other Issues are so low in priority that they should be moved to backlog issues.
