### ISSUE TITLE
Service Provider UI bugs

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkManager#1057]
test 14: unique check is not performed on edition

**Comment by bsaiken** [comment]
> @FWAJL siad:
test 14: unique check is not performed on edition

Did you mean on "addition"?  
What is test 14?

I checked and the unique check is being performed, so I do not understand this Issue.

**Comment by FWAJL** [comment]
@bsaiken 

I have just tested it now on the live site.

When you ***edit*** (not add) a service provide and you set the name to an existing name, the uniqueness of the name is not performed.

![screen shot 2015-07-23 at 07 23 51](https://cloud.githubusercontent.com/assets/7524388/8843676/f8184fcc-310b-11e5-9281-fb0f0122a5f5.png)

This test 14 found here: https://docs.google.com/spreadsheets/d/1p-haRxzmUXgu65BHJHfJoa4cSjrkp-lfma_HRlkVed4/edit#gid=1710625469

**Comment by bsaiken** [comment]
where is this file located?  it is not where it is supposed to be - in 
/google drive/FieldWorkManager/Unit testing files

**Comment by WebDevJL** [comment]
@bsaiken 

Now it is.
