### ISSUE TITLE
Rename repository to FieldWorkManager

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkManager#1059]

**Comment by FWAJL** [comment]
@bsaiken

**Comment by WebDevJL** [comment]
@bsaiken 

Renaming is done. You will need to clone the repository again. The branches were kept and all the commits also.

I released the renamed repository to HurrayHost and changed where the url is pointing. The old repository still exists on the server but it can't be updated of course.

Thank you.
