### ISSUE TITLE
Add a Task checklist

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1060]
For the PM, the checklist will be in the right hand column at: /task/showForm on the Task Info tab.
This will be a simple list, like this:

> Add the checklist form (as a textarea)
> Update the database to include checklist items
> Add a column in the database table for when the checklist item is done (cl_complete===0 - not done; cl_complete===1 - done)

For the FT this will be a new menu item, "Checklist".  Use font-awesome "check-square".
Auto upload the result in to the database (reset cl_complete)
The FT view includes a checkbox.

> [ ] Add the checklist form (as a textarea)
> [ ] Update the database to include checklist items
> [ ] Add a column in the database table for when the checklist item is done (cl_complete===0 - not done; cl_complete===1 - done)

FYI - this will be used to determine if the Task is "complete".

See also Issue #1062.

**Comment by WebDevJL** [comment]
@bsaiken 

New table task_check_list to record a row per checklist item for a task.

- table `task_check_list`
  - `task_id` ; int ; FK table task
  - `task_checklist_id` ; int ; PK
  - `task_checklist_detail` ; varchar(size???)
  - `task_checklist_complete` ; tinyint ; 0 or 1 (default=0).

**Comment by FWAJL** [comment]
@bsaiken Can you confirm the size of text you want for the checklist elements? 100? 250?

Other than that, I think the specifications are clear enough but I might add:

1. The PM can edit the checklist when task is not active.
2. The PM can only view the checklist when task is active.
3. The FT can only checks the checklist items for a task.

Have we got a task planned to refresh the checklist items status on the PM Active View interface?

**Comment by bsaiken** [comment]
@damirius @gsouvik 

FYI:  split this into several smaller Issues under the "Checklist" Milestone.
