### ISSUE TITLE
In the FT map view, auto zoom to Task locations (not Project Locations).

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1064]

**Comment by damirius** [comment]
@bsaiken 

Set initial zoom for mobile map to task locations. 
When setting up initial zoom script will first try to fit all Task markers in the view, if there are no task markers it will try to fit all markers (project), if there is only one marker it will center on that marker and if there are no markers it will zoom to project boundary.
So just like before with addition of that first step with task markers.

Commit is on feature_damir branch

**Comment by bsaiken** [comment]
@damirius 
Looks good.  Make sure you are working in order of priority.
