### ISSUE TITLE
Locations drag and drop must be removed from mobile UI map (smartphones only).

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1066]
Prerequisite: #1067.
Related to #1074 and #1075 
Also, the mobile map for a smartphone should be the entire page.   Remove the location list and any margins.

**Comment by WebDevJL** [comment]
@bsaiken 

The issue title and the description are not related. Are they two tasks to complete?

**Comment by bsaiken** [comment]
@WebDevJL 
I disagree - the Issue title and description are indeed related.  There are multiple related Issues.
