### ISSUE TITLE
Change Field Analytes to "Field Data" 

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1068]

**Comment by WebDevJL** [comment]
@bsaiken 

More description please.

**Comment by bsaiken** [comment]
@WebDevJL 
Question.  I just changed all the text that says "Field Analytes" to "Field Data".  I had to change this in many files.  Doesn't it make more sense to have a common resource file so that I only have to change the text in one location?

**Comment by WebDevJL** [comment]
@bsaiken 

Yes, it makes sense.

You need to define a new common variable in `BaseController->AddCommonVarsToPage` (see line 244 => `$resx_left_menu = $this->app->i8n->getCommonResourceArray(Enums\ResourceKeys\ResxFileNameKeys::MenuLeft);`).

You need to give a name: "resx_data" and you get the data using the resource file name (add a ResxFileNameKeys and set the constant value to be your resource file name).

You can create a generic_resource for example in Applications/PMTool/Resources/Common.

I hope that helps.

**Comment by WebDevJL** [comment]
@bsaiken 

If I am correct, this is related to #1094, isn't it? Can you update the status, please? (release or not)
Thank you.
