### ISSUE TITLE
When uploading a document, including a photo, the "upload" button can not activate until the document has uploaded (otherwise it is lost).

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1069]
This needs to be true in all cases, for the PM and the FT.

**Comment by WebDevJL** [comment]
> @bsaiken said:
> the "upload" button can not activate until the document has uploaded

What does it mean?

**Comment by bsaiken** [comment]
@WebDevJL 
Try uploading a photo for a technician.  If you start the upload a photo using fancybox, and click "Save" before the document is uploaded, the photo will not be save, even though I get a "success" message.

**Comment by damirius** [comment]
@bsaiken 

On feature_damir branch.

Here's the list of pages where I updated the forms.
Edit Technician, Edit Location, Map Location infowindow and Task Location infowindow, Active Task notes/communications/map.
Forms are autosaved on file upload.
On mobile UI: Map both location and task location infowindow, location list for location and task location infowindow and add new location infowindow, notes, communications.

**Comment by bsaiken** [comment]
@FWAJL 
Jeremie,  This really cannot be tested properly unless I am in the field, so I pushed it straight to code review.

**Comment by damirius** [comment]
@bsaiken 

Yea on local server upload time is short so buttons are disabled for only split second. Like you said it will be better to test it out on remote server.

**Comment by bsaiken** [comment]
@damirius 
I did not check each implementation, but the ones I checked worked, so closing for now.
