### ISSUE TITLE
Mobile UI must be updated so on each page everything fits on a smaprtphone screen.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1072]
![img_3287](https://cloud.githubusercontent.com/assets/8228624/8506337/6781c6d2-21d4-11e5-80d9-032f3d782dac.PNG)
![img_3288](https://cloud.githubusercontent.com/assets/8228624/8506338/67840316-21d4-11e5-9b2d-ac5c07f708c9.PNG)

**Comment by WebDevJL** [comment]
@bsaiken 

Do you mean no vertical scrolling ever?

**Comment by bsaiken** [comment]
@WebDevJL 
Vertical scrolling may be needed sometimes.  If that were the only problem I would not have made the Issue.  There are much larger problems with the display.  However, in this example, all of the information for the info window, if it were properly formatted, could be made to fit without any vertical scrolling.
