### ISSUE TITLE
Update FT Map view for smart phones. 

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1074]
Related to #1075.
1) Remove the menu functions for the mobile UI map - they are not needed on a smartphone interface and some just don't work well.
2) Add location labels for all Task locations (only).  The labels do not need to appear until the user zooms in.
3) Remove the location list from the map view - we added a new view for the location list (#1075).
4) Have the map view fit a smartphone screen.

http://stackoverflow.com/questions/1056330/how-to-display-a-label-next-to-a-marker-for-google-maps

**Comment by WebDevJL** [comment]
@bsaiken 

What are on-screen menu functions?

Did Damir do the drag&drop on the map?

**Comment by bsaiken** [comment]
@WebDevJL 

> What are on-screen menu functions?

These are all on-screen menu functions:
![img_3325](https://cloud.githubusercontent.com/assets/8228624/8549148/c4f696fa-248e-11e5-916f-c19cc639dcdd.PNG)

> Did Damir do the drag&drop on the map?

The PM can drag and drop locations to a new position and the new coordinates are automatically updates.  This behavior must be removed for a smartphone.  I think it is OK for a tablet.

**Comment by bsaiken** [comment]
For clarity,  rather than worry about smart phone detection right now, we just need to make this change for the mobile UI.  Perhaps comment out the code we do not need so we could go back to it later, if desired.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Hey guys!
I'm home again so I can start working on this issues. I see that this is one have highest priority so I'll start with it. 
I'll update and setup everything on my local machine asap. If I have some questions I'll ask them here when I start working on specific stuff.

**Comment by bsaiken** [comment]
@damirius @FWAJL @gsouvik 
Good to have you back, and much needed.
Field testing revealed that the mobile map UI does not work at all - we need a major overhaul.  Note that I just re-opened #1075 for you to fix properly.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

I see that some stuff is already done here. For example custom controls were removed already.
In any case, I've removed default google map UI for mobile map also.
I've also added infobox label class. When user zooms in labels will show up, zoom level threshold is set to 15, it can be changed if you wish.
Other than that I've opened up the map in chrome's phone emulator and also on my nexus 5, map is showing over whole screen so I can't see any problems with that currently.
Tell me if anything else needs to be done as part of this issue.

You can see all changes on feature_damir branch.

**Comment by bsaiken** [comment]
@damirius 
Yes, I already did some things, but I needed your expertise to finish the job, and in some cases fix my patchwork solution.
Can I change how the labels appear, say with CSS?  If so, point me where this is.
Also, point me to the location of the zoom level threshold parameter.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Have you done a git pull?  Your branch is seems behind.  This could be because the dev branch is lagging the feature_pm branch.

**Comment by WebDevJL** [comment]
@damirius @bsaiken

The dev branch and all feature branches are up to date with code of version
1.7.3.

All code done after that is not merged to all branches.

**Comment by WebDevJL** [comment]
@bsaiken @damirius @gsouvik

See my comment in #1074.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

I pulled everything multiple times, yesterday and few hours ago again.

You can change label box css in mobile_map_manager.js in web/js/app/controllers directory.
It has to be specified in labelOptions object, you can find it on line 620 under 'boxStyle', I believe you can use anything there you would use in regular css.

Zoom level is on lines 710 and 715 in the same file, you'll see 'zoomLevel>=15' in if statement on line 710 and 'zoomLevel<15' in if statement on line 715. Just change 15 to zoom level you wish.

**Comment by bsaiken** [comment]
@damirius 
Where are styling instructions?  For example, if I want to change the font color to yellow, how would I do that?
Also, wouldn't the box styling be in a CSS file - or is that not possible?

**Comment by bsaiken** [comment]
@damirius 
Actually, I was able to answer some of my own questions, but I still think styling should be in a CSS file.

**Comment by damirius** [comment]
@bsaiken 

Well, it wasn't my choice, it's done like that in their class.

**Comment by FWAJL** [comment]
@bsaiken 

Can we close this?
