### ISSUE TITLE
FT can add location

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1079]
In the FT Location list (see #1075), add an icon at the end of the Task Location list with the temporary label (Add Location).  Clicking this will call the Location info view, only the Location field will be blank.  The FT must enter a Location name, or clicking "Enter" will not record the data, which may include the marked location coordinates and a photo.

**Comment by WebDevJL** [comment]
@bsaiken 

1. add an icon at the end of the Task Location list with the temporary label (Add Location) => can you make a visual mockup please?
2. Clicking this will call the Location info view, only the Location field will be blank => location info view is the prompt box?

**Comment by bsaiken** [comment]
@WebDevJL 
> can you make a visual mockup please?

Instead of this:  
![img_3323](https://cloud.githubusercontent.com/assets/8228624/8548794/a0b1b290-248c-11e5-8545-a050caa10dad.PNG)

This:
![img_3324](https://cloud.githubusercontent.com/assets/8228624/8548804/aa9cef86-248c-11e5-9578-a5f7cd4ac38b.PNG)

> location info view is the prompt box?

Yes

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I went through the list of the issues with high priority. I needed to start somewhere so I decided to pick this one. I'll need a bit of more information before I could start on this.

I was able to login as a technician using my mobile device and open the list of locations. I also understand that you wish to add an icon as shown on the second slide. After this, the requirement is not clear to me. Please explain what happens when the technician taps the icon. Will he be able to add a location into the location table?

Thank you.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Good question.  I will be very specific, but the simple answer is that this is really just the difference between `Add` versus `Edit`.  We already have the `Edit` function established.  We also have a separate form for editing a Task Location that does not have any coordinates.  Any time you click on any of the Task Locations a popup appears with the `Edit` form.  The only difference here is the location name is not already populated, it is editable, and it is a required value.

You see on my mockup where there is an item listed under `Task Locations` that is titled `Add New Location`.  This item is not a Location where `location.location_name = Add New Location`, rather, you can think of this as a button.  Using this "button" the FT will be able to add a new Location into the database.  This entry should always be on the top of the Task Locations list.

You can use the existing form as a starting point.  The form shall have two buttons, "Add" (instead of "Update")  and "Cancel".
Clicking the "Add" button on the form shall save the following information into the database:
`location.location_name` (from the form)
* Check to make sure this is unique. 

`location.location_active=1
location.project_id` (session value)
`task.task_id` (session value)
`task.task_location_status=1
location.location_id` (auto-generated on save)
`task_location_id` (from auto-generated value)
`location.location_lat` (see Issue #1070)
`location.location_long` (see Issue #1070)`
 * Since Issue #1070 is not complete, use the default session values:
`facility.facility_lat` and `facility.facility_long`.

The FT can also use the form (while adding a new location) to input the following optional values:
`location.location_desc`
photo upload

Remove these items from your "Add" form:
`Zoom to selected location`
`Collect Data`
`Directions`
`View photos`
`Mark`

After the values are saved, provide a redirect back to `/mobile/loc_list` and refresh the page. 
Don't forget to update the session array.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
Great, that explained the requirement very clearly. I shall start with this and shall ask you questions if I face any issues. I'm working on the `feature_PM` branch.
Thank you.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I've coded the feature where the FT can add a new location, following is a list of the key features coded for the Issue.
1) Icon added as shown in slide, taping which the FT would be able to add new Location.
2) Tapping the icon, the popup dialog opens with buttons "Add" and "Cancel". The fields are limited to only `location_name` and `location_description` along with photo upload capability. Lat and Long are taken from Session dynamically when adding in background.
3) Unique check added on location name.
4) Tapping on "Add" the FT is able to add the new location. Also the location associates itself with any photos uploaded earlier through this screen.
5) The page reloads and shows the updated list.
I've tested the code and didn't encounter any problem, but the issue was altogether a bit complicated and consisting of multiple areas of functionality. Please test and let me know if you find anything and I shall fix it.
Thank You.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 

This is not going to work.  I set up the `/mobile/loc_list` module, but it was not done properly.  I thought my ad-hoc patch would work, but it won't.  I will need to get this fixed.    

Please go to the next Issue.

**Comment by bsaiken** [comment]
@damirius 

Damir,  I had assigned this to Souvik, and he nearly finished, but I realized this really can't be done properly until #1075 is complete.  Since you have #1075 as your highest priority item, and they are related, I am assigning this to you to finish (after 1075). 

Make sure you coordinate with Jeremie so you can merge Souvik's work (or at least look at it) before continuing.

Thanks!

**Comment by bsaiken** [comment]
@damirius 
Maybe it would be best just to put a button to add a new Location.  See mockup (https://github.com/FWAJL/FieldWorkManager/commit/55cfcfbb4c2daaa0c6532a9d153f3c7df581e04f).

**Comment by damirius** [comment]
@bsaiken @FWAJL 

New commit is on feature_damir branch.
I've added button for adding new task location on the mobile location list. I've used existing js function for calling the infowindow, gsouvik already made webservice for it too so I used that for entering new info in db/sessions.

**Comment by bsaiken** [comment]
@damirius 
I am not seeing the button, or that the html was added, per line 286 or mobile_manager.js.

Also note in the attached photo that the highlighted html, and several lines below, do not need to be there.  Not only were they supposed to have been removed, but they are needed for the map view, and this is just a list of Locations.

<img width="1440" alt="screen shot 2015-08-03 at 12 45 26 pm" src="https://cloud.githubusercontent.com/assets/8228624/9043823/f248ece8-39dd-11e5-8a59-cc0468ab11cb.png">

**Comment by bsaiken** [comment]
@damirius @FWAJL 

False alarm.  I had not done a proper git pull.  OK for Code review.

This really can't be fully tested until we do Issue #1070, so I have promoted it to Very High Priority.

**Comment by FWAJL** [comment]
@damirius @bsaiken 

It is really confusing to use the module `map_info.php` and actually its inner html is set in `mobile_manager.js`.

Rather, it would be better to create a module in `Views/Mobile/Modules` called `locationListContainer.php` and put your empty div in there with a comment explaining how it is used (jQuery append).

Can we do that?

**Comment by damirius** [comment]
@FWAJL @bsaiken 

Sure we can.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

I've created new module for this location list. I've also changed some ids and stuff, so I'm putting this issue back on function review to test it out.

Like always new commit is on feature_damir branch

**Comment by bsaiken** [comment]
@FWAJL @damirius 
Initial testing checks out.  Further field testing (with smartphone, away from wifi connection) required.

**Comment by bsaiken** [comment]
@FWAJL 
I create new Issues for Unit Testing in the field.  I certainly can add Locations, which this issue is for, but there are still problems...
