### ISSUE TITLE
Remove Fazil and testingbydev as contributors.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1080]

**Comment by FWAJL** [comment]
@bsaiken 

They are not contributors already.

**Comment by bsaiken** [comment]
Oh - I saw the attached page.

As far as Issues, notice I have not assigned anyone yet.  Well, except 
me since I'm free labor.  So, no work until assignments are made.

I need to carefully prioritize Issues so we can continue on minimal 
budget until I get more money, or a job.

I can't guarantee I can talk this Tuesday, as you suggested, but it is  
my intention to clear the space.

I am still working on prioritizing and organizing Issues, so once we 
talk I should be ready to move forward again.

Brian

**Comment by FWAJL** [comment]
@bsaiken 

Gotcha! You tell me what to do :+1:
