### ISSUE TITLE
Location Marking evaluation

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1087]
@FWAJL 
Jeremie,
I did a check of the coordinates accuracy for marking locations on the map.  The Location accuracy is pretty good!  The FT does, however, need to set the phone's coordinates, as in #1070.  When I did not do that , the coordinates could be 100's of meters off.

<img width="1440" alt="screen shot 2015-07-10 at 9 07 04 am" src="https://cloud.githubusercontent.com/assets/8228624/8620159/539d2332-26e3-11e5-96a1-574956dc18c9.png">

**Comment by WebDevJL** [comment]
@bsaiken 

Maybe the geolocation API can give accurate coordinates? I think it is a shame to use the native app to get the coordinates as it is not very practical.

Shall we make this issue the issue to implement geolocation API?

**Comment by bsaiken** [comment]
@WebDevJL 
I thought we were using the geolocaiton API.  Perhaps it is just the Google Maps API.  Can you confirm this?

The important message is that the coordinates are accurate enough.  

If we can save the extra step using the geolocation API, of course I will create the Issue.

Brian

**Comment by WebDevJL** [comment]
@bsaiken 

The Google Maps services includes a Geolocation API that uses cell towers, wifi hotspots positions or GPS to calculate yours. 
When using our web interface, we don't have the Geolocation active (see the icon you circled in the last image of #1070). We should add a button that when clicked will ask permission to request coordinates and then the data will call the Google Maps to load the location retrieved. That's the theory.
Also, 4G network QOS does matter a lot in the accuracy if not using GPS!

So again, the blue markers are from what source, maybe your sample project location coordinates? What about the red markers?

**Comment by bsaiken** [comment]
Jeremie,

I have been making some pretty good progress addressing some of these 
issues myself.  While some of my fixes are not terribly efficient, they 
are utilitarian and already make the site significantly more 
presentable.  We are at a stage now where utilitarian will need to win 
out if we hope to move on.

That being said, given the level of complexity and effort I am 
experiencing, I think I could ask Damir or Souvik to have another stint 
of work.  It will help me to know how to proceed if you can be clear 
with me about your availability.  I know we plan to talk next week, and 
that is still a good idea, but do you know now what your schedule will 
be like?

Brian A

**Comment by FWAJL** [comment]
@bsaiken 

I think you didn't answer the questions from https://github.com/FWAJL/FieldWorkManager/issues/1087#issuecomment-120660736. Can you please?

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
Here are the answers to your questions.

> Maybe the geolocation API can give accurate coordinates?

Yes, I agree that it likely could.

> Shall we make this issue the issue to implement geolocation API?

This is Issue #1070.

> So again, the blue markers are from what source, maybe your sample project location coordinates? 

You can see this data if you log in with user "baiken".  You do not need to know anyone's password to login.  Just log in to the admin user and do a switch.  The blue markers are Project Locations.  I identified them as Project Locations so that it would be easy to distinguish them from their corresponding Task Locations.  The fact that they are Project Locations, and the other are Task Locations, has nothing to do with the Task - it was just so they would have different symbols.  The blue maker coordinates are the actual coordinates of the features.  I manually placed the markers onto the (satellite view) map to line up with the features.  If you look closely, you can see the feature I am marking in the satellite image. The marker appears just slightly north of the feature, but this is not exactly true.  If you try to drag and drop one of the blue markers, you will see an "X" that shows the coordinates being marked, and the "X" is directly on top of the feature.  I will want to get this fixed eventually.

> What about the red markers?

The red markers are the coordinates I got when I did a field test using the "Mark" function.  The point I was trying to make is that the coordinates are close enough to be acceptable.  The FT "Marks" the location in the field, and then the PM can manually move the marker into the exact position as long as the aerial image has sufficient detail to do so.  In order for me to get coordinates of this accuracy, I had to open the Google Maps app each time and click the "Target" button.  If I did not do this, the marker coordinates may have been hundreds of feet off, which is unacceptable.  Hopefully, implementing the Geolocation API will eliminate that step.

I am closing this Issue since it is addressed in Issue #1070.
