### ISSUE TITLE
Create an Active Task field data matrix table.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1103]
This is the same table as the field data matrix for inactive tasks.
Shows database values.  If there are no values recorded, show an empty field.
Tab has been created along with views and controller.  The existing output is a mockup.
See Issue #1098 for screen shot of mockup.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
So basically this is the same functionality as that of `task/fieldMatrix` for Active tasks. As I understand I would just have to reuse the code and tables which already exists for the inactive task field data matrix and generate this screen for the Active task. Please confirm and I shall start coding.

Also I've pulled  `feature_devsupport` and plan to code this feature on that branch.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 

The tables are not the same, but it is very similar.  The `task/fieldMatrix` is a table of Locations and Field Parameters with checkboxes (checked or unchecked), so we can create the matrix that defines which of the Location/Field Parameter pairs will be needed.

The `activetask/fieldData` table may have one of three different entries for each Location/Field Parameter pair:

1) The field has a standard text string, "Do not sample", for each Location/Field Parameter pair from `task/fieldMatrix` where the box was unchecked (there is no corresponding row in the `field_analyte_location` table).
2) The value recorded in `field_analyte_location.field_analyte_location_result`.
3) If there is supposed to be a value, but it has not been recorded yet, give me the option to put a standard text string here.  Initially, use "Not yet sampled".  In the mockup (#1098) I showed a checked checkbox, but that is incorrect.  

Brian

**Comment by gsouvik** [comment]
@bsaiken 
So the table is actually same - `field_analyte_location`. Only the functionality is different the way you have explained in your 3 points. 

If for a particular location and field data pair, some data is recorded and the screen is reloaded later, would the user be able to edit that text? In other words, continuing with what you said in your point 3, when the screen is reloaded later, will the text which the user saved earlier for that "location + field data" pair be editable?

Rest of the requirement is clear to me.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
For now make the data un-editable by the PM.

**Comment by bsaiken** [comment]
@gsouvik 
I think I misunderstood your question.  The data is editable.  If the PM is looking at the screen, and the FT changes the value, the PM would not know until they did a re-fresh.  

We implemented an auto-refresh.  I will have Damir work on the auto-refresh, since he did the original refresh work.  Your job is just to create and populate the table.

**Comment by gsouvik** [comment]
@bsaiken 
Understood, I'll keep a note of that while coding.

**Comment by gsouvik** [comment]
@bsaiken 
I've created the Active task field data matrix screen. The code is pushed to `feature_devsupport` branch.
Please review and let me know if any changes are required.

On a separate note, I think I've found a bug on the field and lab matrix screens when the data spans into many pages. The check-boxes do not retain their checked status other than the current page, when the matrix is saved. I discovered the issue while creating a matrix for the test case related to this issue. May be we need an issue to fix it.

**Comment by bsaiken** [comment]
@gsouvik 
This is not working on my local machine.  Is there a database update I need?

**Comment by gsouvik** [comment]
@bsaiken 
The following scripts which were added already and I assume you might have in the database, are needed for the code to work:
https://github.com/FWAJL/FieldWorkManager/blob/master/Database/Scripts/Updates/2015-07-24.sql
https://github.com/FWAJL/FieldWorkManager/blob/master/Database/Scripts/Updates/2015-07-27.sql
https://github.com/FWAJL/FieldWorkManager/blob/master/Database/Scripts/Updates/2015-07-30.sql

If it doesn't work even after applying those scripts, please send some screenshots of the JS console for when the page loads and when you click on the save button.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
Thanks Souvik.  I identified the bug and created Issue #1148.
