### ISSUE TITLE
Create a FT webform for the "Collect Data" button.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1104]
Create a webform from the Field Data parameters.  This will be done instead of using a pdf form.  We can add a link to the pdf form(s) later.

The FT will fill in the form and the data shall be uploaded to the field_analyte_location table.
Include the datestamp for each new field entry and save to `field_analyte_location.field_analyte_location_date` - see Issue #1116.

If some data has been collected, show the data on the form (in red, if possible).

Refresh the page every time the FT clicks "OK" so they can verify their data was collected. 

We need to see the new data each time, to check entries in the field, even if it takes longer.  Does this affect the interaction with the session array?

For related Issues, see https://github.com/FWAJL/FieldWorkManager/milestones/Field%20Data%20Webform.

**Comment by FWAJL** [comment]
@bsaiken 

As briefly discussed yesterday, here are the steps we could take to make sure the data is saved:

1. FT enters the data in the input(s).
2. FT clicks "OK" or "Save". The values are cleared from the inputs (btw, browser won't cache this data unless we tell them).
3. Request validation from FT in a simple popup before initiating the process to save the data. This is to make sure the FT has correctly entered the right data.
4. On the server, the data is saved to the DB.
5. We handle the response after saving the data to the DB.
  a. If the data is saved, 
    - we refresh the page and load the data stored into the inputs 
***OR*** 
    - the server sends as the response the same data (see NB0)
***AND***
    - we disable or hide the "OK" or "Save" button for the parameter just completed.
  b. If the data is not saved, we ask to input and save the data again for the parameter.
6. Once those 5 steps are complete, we enable the next parameter (see NB1).

NB0: This works like a refresh because we don't rely on the data the user entered in the html inputs but rather we rely on the data saved that we can query after save and we return it as the server response to the request.

NB1: I think that in the case of multiple field parameters for a given location, we should enable one save button at a time so that the FT is not tempted to enter all the data, click one save button and think it saves it all. Instead, the FT submits the data one parameter at a time and validating that the data is saved for one allows to move to the next.

NB2: How do you store the data for a parameter like the example screenshot (Counter value and pump setting)? Do you merge the values together and if so, how do you need it to be done?

> @bsaiken said:
> We need to see the new data each time, to check entries in the field, even if it takes longer. Does this affect the interaction with the session array?

I don't think so. We would query the data each time.

Please let me know your feedback.

**Comment by WebDevJL** [comment]
@bsaiken 

A few other suggestions:

- what about preventing the FT to go to the next location until the current one done?
- show the locations done with a marker like a "checked" green marker icon to clearly show the FT it is done.

**Comment by bsaiken** [comment]
> @FWAJL wrote:
here are the steps we could take to make sure the data is saved:
    1. FT enters the data in the input(s).

Yes - obvious first step
>    2. FT clicks "OK" or "Save". The values are cleared from the inputs (btw, browser won't cache this data unless we tell them).

I do not see why the values would be cleared from the inputs.

>  3. Request validation from FT in a simple popup before initiating the process to save the data. This is to make sure the FT has correctly entered the right data.

Not now.  We can add this later if it seems needed.

>    4. On the server, the data is saved to the DB.

Yes.

>  5. We handle the response after saving the data to the DB. 
a. If the data is saved,
        we refresh the page and load the data stored into the inputs 

Yes, and this where I was asking, if data is loading from the database, can we identify it by being red, or grey or some color.  We need some way of knowing the data was saved.  I thought of adding a toastr here, but I also want the FT to be able to read the specific values.  This is why I do not think 3 is needed.

> OR  the server sends as the response the same data (see NB0) AND
            we disable or hide the "OK" or "Save" button for the parameter just completed. 

This implies there is a "Save" button for each parameter.  I only want one "Save" button.

> b. If the data is not saved, we ask to input and save the data again for the parameter.

If the data is not saved, how would the FT know?  Maybe this is a good place to put a toastr comment.  However, if we don't get positive confirmation (5a), it implies the data was not saved.  There is a question of how long to wait.  Perhaps we could put a toastr comment after a certain period, say 10 seconds, if we do not get a positive response, and the comment would be something like "Data not saved.  Try again or manually record the data"

>    Once those 5 steps are complete, we enable the next parameter (see NB1).

I do not want to go parameter by parameter.  The form can be partially complete and this will still work.  If we color code the text for entries that came from the database, the FT will know which parameters have already been recorded.

> NB0: This works like a refresh because we don't rely on the data the user entered in the html inputs but rather we rely on the data saved that we can query after save and we return it as the server response to the request.

You will have to explain what "NB" stands for, but I think I agree with this statement.

> NB1: I think that in the case of multiple field parameters for a given location, we should enable one save button at a time so that the FT is not tempted to enter all the data, click one save button and think it saves it all. Instead, the FT submits the data one parameter at a time and validating that the data is saved for one allows to move to the next.

No, that is not acceptable.  No FT will enter one value at a time.

> NB2: How do you store the data for a parameter like the example screenshot (Counter value and pump setting)? Do you merge the values together and if so, how do you need it to be done?

Values are not merged.  Each value is saved in a separate row in field_analyte_location.field_analyte_location_result.  Maybe I don't understand your comment.  Nobody ever merges values from a webform.

>  @bsaiken said:
    We need to see the new data each time, to check entries in the field, even if it takes longer. Does this affect the interaction with the session array?
I don't think so. We would query the data each time.

OK


>    what about preventing the FT to go to the next location until the current one done?

This is not practical.  Stuff happens.  The FT can come back as often as they need, in any order.  

>    show the locations done with a marker like a "checked" green marker icon to clearly show the FT it is done.

We are already doing this.  The PM sees a different color marker at `/activetask/map`.  Currently, the condition of having a location being "complete" is tied to forms, so we will need to add having a value entered for each of the field parameters as part of that condition, but this is outside the scope of this Issue.  Once I have this working like I want for the PM map, I think we could add it to the FT map.

**Comment by bsaiken** [comment]
I responded - see github

Brian

On 2015-07-30 00:15, FWAJL wrote:
> @bsaiken [1]
> 
> As briefly discussed yesterday, here are the steps we could take to
> make sure the data is saved:
> 
>  	* FT enters the data in the input(s).
>  	* FT clicks "OK" or "Save". The values are cleared from the inputs
> (btw, browser won't cache this data unless we tell them).
>  	* Request validation from FT in a simple popup before initiating the
> process to save the data. This is to make sure the FT has correctly
> entered the right data.
>  	* On the server, the data is saved to the DB.
> 
> 	* We handle the response after saving the data to the DB. a. If the
> data is saved,
> 
> 	* we refresh the page and load the data stored into the inputs _OR_
> 
>  	* the server sends as the response the same data (see NB0) _AND_
>  	* we disable or hide the "OK" or "Save" button for the parameter
> just completed. b. If the data is not saved, we ask to input and save
> the data again for the parameter.
> 
>  	* Once those 5 steps are complete, we enable the next parameter (see
> NB1).
> 
> NB0: This works like a refresh because we don't rely on the data the
> user entered in the html inputs but rather we rely on the data saved
> that we can query after save and we return it as the server response
> to the request.
> 
> NB1: I think that in the case of multiple field parameters for a given
> location, we should enable one save button at a time so that the FT is
> not tempted to enter all the data, click one save button and think it
> saves it all. Instead, the FT submits the data one parameter at a time
> and validating that the data is saved for one allows to move to the
> next.
> 
> NB2: How do you store the data for a parameter like the example
> screenshot (Counter value and pump setting)? Do you merge the values
> together and if so, how do you need it to be done?
> 
>> @bsaiken [1] said:
>> We need to see the new data each time, to check entries in the
>> field, even if it takes longer. Does this affect the interaction
>> with the session array?
> 
> I don't think so. We would query the data each time.
> 
> Please let me know your feedback.
> 
> --
> Reply to this email directly or view it on GitHub [2].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/bsaiken
> [2] 
> https://github.com/FWAJL/FieldWorkManager/issues/1104#issuecomment-126184966
I

**Comment by FWAJL** [comment]
@bsaiken 

NB = Note Bene = i.e. = e.g.

So I'll take what I wrote and modify it according to your input:

1. FT enters the data in the input(s) of each parameter.
2. FT clicks "OK" or "Save" which initiate a request to the server.
3. On the server, the data is saved to the DB.
4. We handle the response after saving the data to the DB.
    a. If the data is saved, the server returns the data saved and we can highlight it in red, grey or any way you want using CSS (*NB)
    b. If the data is not saved, we ask to verify the data and to click the save button again.

Once those 4 steps are complete (1,2,3 and 4a), a location is complete and we can update the marker.

NB: This works like a refresh because we don't rely on the data the user entered in the html inputs but rather we rely on the data saved that we can query after save and we return it as the server response to the request.

> @bsaiken said:
> Values are not merged. Each value is saved in a separate row in field_analyte_location.field_analyte_location_result. Maybe I don't understand your comment. Nobody ever merges values from a webform.

On the screenshot, to me, it looked like one parameter with 2 values, hence the concatenating remark. If they are distinct parameters, then why put them on the same line. In a UI point of view, list them is more standard. What do you think? 

> @bsaiken said:
>> what about preventing the FT to go to the next location until the current one done?

> This is not practical. Stuff happens. The FT can come back as often as they need, in any order.

So as long as locations not completed are clearly in red as not done, then a FT can move to another location if he can save the data at the particular moment for a given location? Maybe then, ask him, like you said, to write down on paper the values?

**Comment by bsaiken** [comment]
> @FWAJL wrote:
On the screenshot, to me, it looked like one parameter with 2 values, hence the concatenating remark. If they are distinct parameters, then why put them on the same line. In a UI point of view, list them is more standard. What do you think? 

This goes back to my comment about the difficulty of preparing a simple mockup in our existing MVC structure.  They are different values, and they should be shown on separate lines, and I would have done so if showing them on different lines would have been easy to do.

> @FWAJL wrote:
So as long as locations not completed are clearly in red as not done, then a FT can move to another location if he can save the data at the particular moment for a given location? Maybe then, ask him, like you said, to write down on paper the values?

a) the FT can move wherever they need to and the website won't be able to stop them.  They may complete the form, partially complete the form, or open the form but enter no values.  We have to accommodate all three instances.

b)  No. The FT would only be notified if the data (which might be a partially completed form) was not successfully saved.

**Comment by FWAJL** [comment]
> @bsaiken said:
> This goes back to my comment about the difficulty of preparing a simple mockup in our existing MVC structure. They are different values, and they should be shown on separate lines, and I would have done so if showing them on different lines would have been easy to do.

By using the method of saving the page with Command+S to your desktop, you can easily modify the page to make a mockup. It is a static page on which you have all the data of the generated page by the server.
We can make it easier for your level of programming, that is good already, but it means to change the way to code it.
Making a list of items in your saved static pages in a breeze for level. Try it please and give me a feedback.

> @bsaiken 
> a) the FT can move wherever they need to and the website won't be able to stop them. They may complete the form, partially complete the form, or open the form but enter no values. We have to accommodate all three instances.
>
> b) No. The FT would only be notified if the data (which might be a partially completed form) was not successfully saved.

Ok, so the most important matter is that the data that the FT inputs and saves is really saved. If he does not complete the job, it is his problem, right?

**Comment by bsaiken** [comment]
> @FWAJL wrote:
By using the method of saving the page with Command+S to your desktop, you can easily modify the page to make a mockup. It is a static page on which you have all the data of the generated page by the server.
We can make it easier for your level of programming, that is good already, but it means to change the way to code it.
Making a list of items in your saved static pages in a breeze for level. Try it please and give me a feedback.

Yes, I'll definitely try that next time.  We hadn't talked yet when I made this mockup.

> @FWAJL wrote:
Ok, so the most important matter is that the data that the FT inputs and saves is really saved. If he does not complete the job, it is his problem, right?

Yes, the  with thec most important matter is that the data that the FT inputs and saves is really saved.

> @FWAJL wrote:
If he does not complete the job, it is his problem, right?

That is a good question.  The best answer I have is that this needs to be addressed with the Build Measure Learn model.  I need to first start recording data in the field and learn from that experience to know what to do when real life conditions arise.

**Comment by bsaiken** [comment]
@FWAJL 
I was thinking about this and I realize that what I want is a very common behavior for web sites, so don't overthink it.  For example, suppose I am trying to buy something on the web and I am filling out the "new customer" form.  Often times, the login name I pick is already chosen, so the page refreshes and it asks me for a now login name.  However, all the other fields that I already filled out, like my address and phone number, are pre-poplutated.  Otherwise, I have to fill in all the fields again (very annoying).  Same idea here.  The FT can partially complete the form at any time then come back and finish.

**Comment by FWAJL** [comment]
@bsaiken 

Ok. Now I think we have all the requirements with your last comment. So, what needs to be done is:

1. FT enters the data in the input(s) of each parameter.
2. FT clicks "OK" or "Save" which initiate a request to the server.
3. On the server, the data is saved to the DB.
4. We handle the response after saving the data to the DB. a. If the data is saved, we can highlight the data saved in red, grey or any way you want using CSS. If the data is not saved, we notify the FT.
5. Every time a FT opens the form to collect data for a or several parameter(s), we load the data saved if any.

That concludes the specification discussion.

Can you validate it (repost the points above modified if necessary) and assign it, please?

Thank you.

**Comment by gsouvik** [comment]
@FWAJL @bsaiken 
I've understood the requirement, thank you for explaining it point wise and elaborately. I just have one point to confirm. So the web form in question would have rows with the field analyte name and the text box for entering the parameter. Something like the following?

FA1     [ text box for parameter ]
FA2     [ text box for parameter ]
.....................
.....................
[ Save button ] [ Exit button ]

Please confirm and I'm ready to start with this issue.
Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
Yes.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I've coded the new Web form. The old code for showing the PDF is present but commented out. I've coded it exactly like the requirement was listed. So that may serve as steps to test. Code is pushed to `feature_devsupport`.

Please review and let me know. Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
Perfect!
