### ISSUE TITLE
Remove user name from mobile top header display

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1113]
This was not displaying properly, and is not needed for the mobile user.

**Comment by bsaiken** [comment]
@FWAJL 
Did you add the text "Check" to the page.  It is showing up now.

**Comment by bsaiken** [comment]
@FWAJL 
Ughhhhhh!.  Nevermind.  It's part of the task name.  This needs to appear entirely in the header...

I commited a fix, but there are problems I need you to address.

**Comment by FWAJL** [comment]
@bsaiken 

What issues are they?

**Comment by bsaiken** [comment]
@FWAJL 
I believe the problem was our old nemesis - you and I on GIT at the same time (or Souvik).  Anyway, I like your elegant approach, but the PM header is now messed up.  I will fix it and re-submit the code.
