### ISSUE TITLE
Merge #1133: conflict in file Views/Mobile/viewList.php

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkManager#1134]
@damirius @gsouvik 

Please help me pick the right code for this file. You modified the same file and I'm not sure what to take.

@damirius's version:
https://github.com/FWAJL/FieldWorkManager/blob/feature_damir/Applications/PMTool/Views/Mobile/viewList.php
@gsouvik's version: https://github.com/FWAJL/FieldWorkManager/blob/feature_PM/Applications/PMTool/Views/Mobile/viewList.php

Is that portion 
```
<div id="mobile_list_map" class="col-lg-1 col-md-1 col-no-pad">
        <p>
          <?php require $form_modules[\Applications\PMTool\Resources\Enums\ViewVariablesKeys::map_module]; ?>

        </p>
      </div>
```
to removed?

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
I believe this follows from the same logic as #1135.  Damir's code should be used.
https://github.com/FWAJL/FieldWorkManager/issues/1135#issuecomment-127040317

**Comment by FWAJL** [comment]
@bsaiken Ok!
