### ISSUE TITLE
Lab Analytes > List All bug

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1145]
From here:

<img width="1440" alt="screen shot 2015-08-04 at 10 41 04 pm" src="https://cloud.githubusercontent.com/assets/8228624/9077947/0aa7e830-3afa-11e5-9d9a-9a9350444062.png">

Click on Lab Analytes > List All (Left Menu) to get this error:

<img width="1440" alt="screen shot 2015-08-04 at 10 41 08 pm" src="https://cloud.githubusercontent.com/assets/8228624/9077951/2238c35c-3afa-11e5-960f-1eecfe653186.png">

What is the error so I can assign it.

**Comment by bsaiken** [comment]
@WebDevJL 
All links are broken:
Lab Analytes > List All
Lab Analytes > Upload List
Field Data > List All
Field Data > Upload List

This is adversely impacting my ability to do unit testing, hence the Very High Priority.

**Comment by bsaiken** [comment]
@FWAJL 
See #1167

**Comment by FWAJL** [comment]
@bsaiken It seems to be fixed in release 1.7.7.

**Comment by bsaiken** [comment]
@FWAJL 
I think it is because I merged Damir's work to DEV, and the problem was not there.
