### ISSUE TITLE
Query database directly to retrieve field data at `/activetask/fieldData`

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1151]
See comment at https://github.com/FWAJL/FieldWorkManager/issues/1130#issuecomment-128263121.

All fields should update on page refresh, or when the user navigates to the page.

**Comment by FWAJL** [comment]
@bsaiken The website is already doing that.

**Comment by FWAJL** [comment]
@bsaiken but this issue includes the auto-refresh, I bet! Does it?

**Comment by bsaiken** [comment]
@FWAJL 

NO, I MADE SEPARATE ISSUES FOR THE auto-refresh.  iF THIS IS done we can close.
