### ISSUE TITLE
Query database directly to retrieve Location information at `/activetask/map`

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1152]
See comment at https://github.com/FWAJL/FieldWorkManager/issues/1130#issuecomment-128263121.

All fields should update on page refresh, or when the user navigates to the page.

**Comment by damirius** [comment]
@bsaiken @WebDevJL 

Locations are fetched directly from db. So if you are logged in as PM you will see changes on location list page and on location/task location maps when you refresh. Same goes for FTs, if you are on location list page or on map page you will see changes when you refresh the page. Infowindows for both task locations and project locations are refreshed on open. So if PM/FT edits the location info, others will see the changes when they reopen it. It also works for PM removing locations from tasks and FT adding new task locations through the location list page.

As always commit is on feature_damir branch.

**Comment by bsaiken** [comment]
@damirius 
Thanks.  My internet is down, so I can't test until later today.

**Comment by bsaiken** [comment]
@FWAJL 
Actually, Jeremie, I will not be able to test this in the foreseeable future unless you push this to dev.
