### ISSUE TITLE
Query database directly to retrieve data at `/activetask/showForm`

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1153]
See comment at https://github.com/FWAJL/FieldWorkManager/issues/1130#issuecomment-128263121.

All fields should update on page refresh, or when the user navigates to the page.
This includes project notes.

**Comment by damirius** [comment]
@bsaiken @WebDevJL 

I mentioned this on the issue #1062, notes already are fetched directly from the DB, so even when FTs add new notes for that task refresh should display them.

Which other fields can be changed by someone else on that page, by someone else I mean someone who isn't logged in PM?

**Comment by bsaiken** [comment]
@damirius 
We are displaying % complete, and this value will (eventually) depend on the FT activities.  However, in the grand scheme of things, I'd rather leave it as a bug for now since we have higher priority issues.

**Comment by bsaiken** [comment]
@damirius @gsouvik 
Damir - I moved this over to Souvik because:
a) you have a lot more high/medium priority Issues outstanding and 
b) I want to make sure Souvik is on board with the need to query the database directly in active task cases.

**Comment by damirius** [comment]
@bsaiken @gsouvik 

Sure, I wanted to ask you about this issue, like I mentioned in my previous comment, notes and new checklist is already directly fetched from the db.
So that leaves only that task completeness which should depend on ft activities and we left it at that.

**Comment by bsaiken** [comment]
@gsouvik 
One option is to close this Issue because fetching the % complete will have a prerequisite (to calculate % complete).   
However, there could be other dynamic data I add to this page (again, we could wait on this since it's a future thing).  

Is it possible to set it up so all information that is retrieved for the active task module is queried directly from the database?

**Comment by gsouvik** [comment]
@bsaiken 
Yes, it can be done, every time the page loads, the data is queried directly from the database. Let me know and I shall start coding. this is only for the `activetask/showForm` `Tak Status` tab or do you want me to check every tab under the active task section.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
Damir is doing the other tabs.  Most of them are done.  You may want to check the code to make sure you are consistent.

**Comment by gsouvik** [comment]
@bsaiken 
I've changed code such that the task details are fetched from DB every time the user visits this page.

**Comment by bsaiken** [comment]
@gsouvik 
In this case it is hard to do a function review since none of the data is available yet, so I am sending it straight to Jeremie for code review.
