### ISSUE TITLE
Add checklist to `/task/showForm` tab.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1167]
Complete the functions for the `/task/showForm` tab.

Items entered in the left hand column appear as checklist items in the right hand column.  The behavior is very similar to `ananlyte/uploadList`.  If you look a the `task/showForm` mockup, this should be fairly self explanatory. 

Display checklist items in the right hand column with an unchecked checkbox, as the items will appear at other urls.

Checklist items in the right hand column are editable (and may be deleted).

Use the new table from Issue #1166.

**Comment by gsouvik** [comment]
@bsaiken 
The `/task/showForm` screen looks like the following:

![screen shot 2015-08-08 at 1 08 26 am](https://cloud.githubusercontent.com/assets/2292482/9144401/4c8dd4e0-3d6a-11e5-9474-6ab37a059787.png)

By left hand column do you mean Data collection and services. The `ananlyte/uploadList` URL is not working on my branch. 

It would be great if you could share the mockup link you referred and explain the requirement in bit more details. Also do I have to create a table for this requirement?

Thank you.

**Comment by bsaiken** [comment]
@gsouvik @WebDevJL 

You need to look at the mockup on `task/showForm` "Checklist" tab.  You can see it at this URL (must be loggin in first):
http://dev.fieldworkmanager.com/task/checklist


I am aware of the problem with `ananlyte/uploadList`.  I had fixed this and committed the code but somehow it got lost in the mix.  The problem is that AnalyteHelper.php is trying to access the file `/Applications/PMTool/Resources/Enums/AnalyteTabKeys.php`, which acciendtally has been overwritten to `/Applications/PMTool/Resources/Enums/~AnalyteTabKeys.php`.  
This code is deprecated, since we are not using tabs any more on our analyte views, but the function still exists.

Commenting out lines 433 and 434 in AnalyteHelper.php solves the problem.
`//        \Applications\PMTool\Resources\Enums\AnalyteTabKeys::FieldTab => "active",`

`//        \Applications\PMTool\Resources\Enums\AnalyteTabKeys::LabTab => ""`

Jeremie, if you can make the change on the DEV branch and merge it back it should resolve Issue #1145.

For some reason, I can't fix it from my end.

**Comment by FWAJL** [comment]
@bsaiken See https://github.com/FWAJL/FieldWorkManager/issues/1145#issuecomment-129042029.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I've coded the Task check list tab. The following points are done and are sub parts of the Issue which can be tested:
1) All the template code which was there was static, this is made dynamic along with the Task tab selection.
2) Batch upload of Task check list.
3) Task check list delete functionality with confirm box.
4) Task update (edit) with duplicate checking alert box.

I've kept the checkboxes on the right hand column as it was shown on the static page. I'm unsure how those are supposed to work, so I didn't add any functionality related to those. Please review and let me know, if any changes are required.

Thank You.

**Comment by bsaiken** [comment]
@gsouvik 
Am I missing a database update?

<img width="1440" alt="screen shot 2015-08-13 at 9 53 33 am" src="https://cloud.githubusercontent.com/assets/8228624/9253021/4f7f10b6-41a1-11e5-90ce-220830c504d6.png">

**Comment by gsouvik** [comment]
@bsaiken
Please use the following and let me know if that worked: 
https://github.com/FWAJL/FieldWorkManager/blob/feature_devsupport/Database/Scripts/Updates/2015-08-08.sql

**Comment by bsaiken** [comment]
@gsouvik  @FWAJL 
Interestingly, I got the same error, even though I had not yet run the script.
I even went to the extent of deleting the site on my local machine and re-installing it.  No luck.

If the solution isn't obvious, respond and let Jeremie know.  I will have Jeremie do a function review, and if it works, release to the dev site so I can do unit testing.

<img width="1440" alt="screen shot 2015-08-13 at 10 14 56 am" src="https://cloud.githubusercontent.com/assets/8228624/9253605/4c44c38e-41a4-11e5-8429-799e10764a85.png">

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
The only reason the error might show up is - the `TaskCheckListController.php` is not properly pulled or not updated to latest code. My latest code was pushed to `feature_devsupport`. I think @FWAJL can give it a try testing the issue and see if it's working.

**Comment by FWAJL** [comment]
@bsaiken @gsouvik 

Works for me. Will look at it in more details before the release.

**Comment by FWAJL** [comment]
@bsaiken @gsouvik 

A suggestion: do we need the checkout to be checkable? It doesn't make since this is to be used in the task execution, e.g. while it is active.

Let me know.

**Comment by bsaiken** [comment]
@FWAJL @gsouvik @damirius 
The checkboxes should *not* be checkable on either of the PM pages.  #1170, #1167
The checkboxes *must* be checkable on the FT page.  #1169

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
I realize my mockup showed the checkboxes as checkable.  I'll try to be more careful next time!

**Comment by bsaiken** [comment]
@gsouvik 
I get no response.

**Comment by gsouvik** [comment]
@bsaiken 
I'm sorry but I didn't understand your last message. Reading the thread, do you want me to remove the check boxes altogether, or let them be there, but in a NOT checkable state.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
I want there to be (empty) checkboxes, but they are not in a checkable state.  

Similarly, for Issue #1170, the PM can see the checkboxes, but the state is not editable.  Simply display the state that is recorded in `task_check_list.task_check_list_complete`.

**Comment by FWAJL** [comment]
@bsaiken @gsouvik 

Is this not done and live? I don't understand the last comments.

**Comment by FWAJL** [comment]
@bsaiken ok so the real matter here is that it is not working on live. I'm investigating.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
On my branch the checkboxes were already deactivated. In the last commit I've added the code which tests the condition:
`task_check_list.task_check_list_complete`
and checks the checkboxes.

**Comment by FWAJL** [comment]
@bsaiken @gsouvik There is an issue with the naming of the TaskChecklist controller and dal. Please verify everywhere that "list" has a lower case "l". I have fixed the controller but the Dal class doesn't work on the live server.

**Comment by bsaiken** [comment]
@gsouvik @WebDevJL 
This is not working for me on my local machine of on the live server.

**Comment by FWAJL** [comment]
@bsaiken It is not fully fixed. Please wait that we fix it. However, the problem is identified.

**Comment by gsouvik** [comment]
@bsaiken @WebDevJL 
Looking at the issue! Let you know shortly.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I've changed the DAL reference from `TaskCheckList` to `TaskChecklist` in the helper file. But I cannot find any difference in test results as it was working earlier also and working now as well on my local (If needed for debugging, I can share video or screenshots).
Please test and let me know if the issue persists with screenshots of firebug. Also please share a credential on live where I may test it as well.

**Comment by FWAJL** [comment]
@bsaiken @gsouvik 

The bug passed my testing because my machine didn't have a case sensitive processing of the class and/or file names. On the live server, if you call a class "TestClass" and "Testclass", it is distinct and will be work in autoloading the file.
I will test on my machine again tomorrow.

**Comment by bsaiken** [comment]
@FWAJL @gsouvik 
Yes!
