### ISSUE TITLE
Add a new "Checklist" tab at `/activetask/showForm`

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1170]
Show the checklist (from #1169) the left hand side.  Issue #1167 is a prerequisite.

Checklist is not editable.

Have the tab auto-refresh (see #1130).

**Comment by damirius** [comment]
@bsaiken @WebDevJL 

Added checklists to activetask. They can't be modified from there, only FT can modify their status on mobile/checklist page.

On feature_damir branch

**Comment by bsaiken** [comment]
@FWAJL @damirius 
OK to push to live site for unit testing.
