### ISSUE TITLE
Move active task notes to new tab.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1171]

**Comment by bsaiken** [comment]
<img width="1440" alt="screen shot 2015-08-24 at 1 10 31 pm" src="https://cloud.githubusercontent.com/assets/8228624/9448300/88921f4c-4a61-11e5-875c-1a6c1be2cdc0.png">

**Comment by FWAJL** [comment]
@bsaiken fixed

The route was misconfigured. The action was "Notes" when it should always lower case.

**Comment by bsaiken** [comment]
@FWAJL 
btw - I'm always on your case about having too many labels, but this "hotfix" label, now that I like.
