### ISSUE TITLE
FT view needs to be overhead.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1175]
This in new, so I think recent code changes caused this.

When I try to look at aerial images, and I zoom in past a certain level, I get the side angle view.

<img width="1440" alt="screen shot 2015-08-07 at 12 57 03 pm" src="https://cloud.githubusercontent.com/assets/8228624/9142522/d5cd63f2-3d05-11e5-93c5-020a32cda51b.png">

We must have overhead aerial views, like this:

<img width="1440" alt="screen shot 2015-08-07 at 12 56 58 pm" src="https://cloud.githubusercontent.com/assets/8228624/9142500/a9041bb8-3d05-11e5-9871-9bd4568c2619.png">

**Comment by damirius** [comment]
@bsaiken 

This should be fixed. Google is adding angle view for some cities. I've added new param for google maps options which should force overhead view.

**Comment by bsaiken** [comment]
@damirius 
This does appear to solve it.
