### ISSUE TITLE
Change text at `/task/fieldMatrix` from Analyte to Field Data

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1187]
@FWAJL 
As I was working on this, I noticed that the checklist tab is broken.  I don't think it is possible it was anything I did.   Still, you should look out for the problem when doing your code review and QC checking.

**Comment by FWAJL** [comment]
@bsaiken 

It is not broken Brian. You must be missing something, very likely to be the table in the database. 
On the feature_PM branch, the tab works for me.

Anyway, your update is ok to release.

**Comment by bsaiken** [comment]
@FWAJL 
I must have gotten behind on the database updates.  Working fine now.  Thanks!
