### ISSUE TITLE
If there is only one Technician, automatically set at `/activetask/communications`

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1189]

**Comment by gsouvik** [comment]
@bsaiken 
I have a question on this issue too, looking at the following screenshot:
![screen shot 2015-09-02 at 11 44 50 pm](https://cloud.githubusercontent.com/assets/2292482/9640047/10741a60-51cd-11e5-95e4-aa858d751fef.png)
Do you want to have the technician selected automatically on the right hand column. But it could be deselected using a mouse click. Please describe what the functionality should actually be.
Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
Yes, select the Technician on the right hand side automatically, if there is only one Technician.

No need to de-select.  If there is more than one option on the right hand side, auto-selection does not happen, and the user must make a selection.

**Comment by gsouvik** [comment]
@bsaiken 
I've implemented this feature. When single technician is available, it is automatically selected and all communication data is loaded.

I've refactored code from ActiveTaskController and moved it to ActiveTaskHelper so that we may reuse maximum of the code which was already written. Please review and let me know.
Thank you.

**Comment by FWAJL** [comment]
@gsouvik Go initiative refactoring into the Helper. However, also think about splitting function so that are short. You could make 4 functions of the one you moved. One for each if.

**Comment by bsaiken** [comment]
The first time I tried this it did not work.  If the FT were selected, it would appear in the breadcrumb.
<img width="1440" alt="screen shot 2015-09-03 at 3 36 43 pm" src="https://cloud.githubusercontent.com/assets/8228624/9670408/0218956a-5252-11e5-894c-caeaca27875f.png">
@gsouvik

**Comment by gsouvik** [comment]
@bsaiken 
The functionality was working but the breadcrumb was not updating the technician name, I've fixed it. As usual, code is pushed to feature_devsupport.
