### ISSUE TITLE
Improve coding efficiency with the FWM site - Step 1

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkManager#1191]
Step 1: saving the page locally to view it and modify it

@bsaiken are you satisfied with this method?

**Comment by bsaiken** [comment]
@WebDevJL 
I have not idea what you are talking about.  I don't want you to spend any more time on "coding efficiency".  We make the code more efficient when it does what I want.  I have been field testing and there are many problems.
