### ISSUE TITLE
Task activation from Task info tab

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkManager#1193]
@bsaiken 

Just a remark as I'm setting testing data: when you click "Activate task", the PM doesn't know if anything happened and the button "Activate" doesn't change to "Deactivate".

Should we not have the PM redirected to the Active Task UI?

**Comment by bsaiken** [comment]
@FWAJL 
I don't know what you are checking, but it does redirect.

**Comment by FWAJL** [comment]
@bsaiken

I'm not checking anything. I just click "Activate tak" button in the task
info tab. I will check again locally.

**Comment by FWAJL** [comment]
@bsaiken Some bug happened but is not there. Closing.
