### ISSUE TITLE
Automatically add Task Field Data parameters when editing a Task

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkManager#1197]
See #1061 for details.

**Comment by bsaiken** [comment]
@WebDevJL 
I could have used this feature for a project I was setting up today, so I moved it to Very High priority.

**Comment by FWAJL** [comment]
@bsaiken this is my next task. Please allow a little more time to complete. It takes more than the locations and technicians. Thank you.

**Comment by FWAJL** [comment]
@bsaiken I have to answer comments on #1201. Which is most important?

**Comment by bsaiken** [comment]
@FWAJL
I may have #1201 sorted out.  This is higher priority, although we have several related bugs that will prevent me from using the site this week for my field work.  My field work is happening Wednesday, so I will not be able to Skype.
