### ISSUE TITLE
Directions upgrades

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1203]
Directions is not working.  Isn't it possible to just have the address, or coordinates, open the phone's map tool with the the address as the destination?

**Comment by damirius** [comment]
@bsaiken 
It is possible, I can change it if you wish. However I don't know what's wrong with our built in directions?
I've tried it and it works for me https://drive.google.com/file/d/0B7Laiv0PjSvDdG03dUh6cEE0SjQ/view
It isn't as detailed as in app I guess.

**Comment by bsaiken** [comment]
@damirius 
Yes, I see the same thing, but this is not useful in the field.  
Comment out the dropdown (Walk/Dive) menu.  When the user clicks "Diresctions" open a map app with selected the coordinates as the destination.  Can that be done?

**Comment by damirius** [comment]
@bsaiken @WebDevJL 

I've added hyperlink for directions which should open up maps app. I've tested it on my nexus (android), but it would be great if you can tell me if it opens up like it should on iPhone too.
Here is the video: https://drive.google.com/file/d/0B7Laiv0PjSvDMGNReFRZdVBOVFk/view
Note that I tested geolocation button in this video too, this isn't necessary to do before clicking directions, just wanted to test it out while I was recording.

Commit is on feature_damir branch.

**Comment by bsaiken** [comment]
@FWAJL 
I need this pushed to dev to test.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Looks good.  I just need to do a field test now.
