### ISSUE TITLE
Map and aerial views for the FT

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1204]
I realize the FT will need to have both the the aerial and map view.  Aerial should still be the default, but replace the buttons on the screen to switch between aerial and map views.  Once the FT has chosen a view, the viewtype should be remembered and used if the FT navigates away and returns.  The default would only be needed right after login.

**Comment by damirius** [comment]
@bsaiken 

When you say map and aerial view you mean that angle view we removed right or am I missing something here?

**Comment by damirius** [comment]
@bsaiken @WebDevJL 

I've added back maptype control for mobile map. Maptype is saved on switch for whole session until logout.

Commit is on feature_damir branch.

**Comment by bsaiken** [comment]
@FWAJL @damirius 
Jeremie, I need this pushed to the dev branch to test.
