### ISSUE TITLE
FT location on the map

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1205]
@damirius 
Is it possible to see the current location of the FT on their map (so they can orient themselves in the context of the Task Locations)?

**Comment by damirius** [comment]
@bsaiken 

We can show FT's location. Do we update it only once when FT opens up a map or we should refresh it automatically like in navigation apps? Or maybe the third option, we show him his location and add some button for refreshing manually?

**Comment by bsaiken** [comment]
@damirius 
To be honest, I am not sure what to do, so whatever it is should be simple and quick.  How easy would this be:
Add a button, located near the Map/Satellite buttons.
Clicking this button re-centers the map to the FTs current location.  If the coordinates need to be retrieved, don't ask, just get them.
Show the location with a blue dot, but have the current FT coordinates be static and fade out over a 30 second period.

**Comment by damirius** [comment]
@bsaiken @WebDevJL 

I've added "current location" button as the part of google map's custom control group.
You can see it in the top right corner below maptype option switch.
Clicking on it will try to fetch your current location, I'm using that updated geolocation function which we used for higher accuracy so wait time is 15secs. When coordinates are returned, map should center over the marker (no zoom) and button should turn light blue (similar to google maps). After 30 secs, button should turn gray once again and marker will be removed.
You can style the button in app-mobile-theme.css

Like always commit is on feature_damir branch.
