### ISSUE TITLE
Error editing Field Analyte text

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1206]
<img width="1440" alt="screen shot 2015-08-13 at 9 14 37 pm" src="https://cloud.githubusercontent.com/assets/8228624/9265957/71b469ce-4200-11e5-9c85-de79028f2b3e.png">

**Comment by bsaiken** [comment]
I think this happened with I tried to edit a field parameter name and the entry was a duplicate.

**Comment by FWAJL** [comment]
@bsaiken It is not a javascript error anything you this. It is from the PHP.

Anyway, it is fixed.
