### ISSUE TITLE
Field Matrix table checkboxes not saving

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1236]
The field data matrix table checkbox states are not saving.  Also, there is no indication for the user that the save happened.  We need to add back in the toastr comment here.

This is a prerequisite to Issue #1202.

<img width="1440" alt="screen shot 2015-08-18 at 9 22 39 am" src="https://cloud.githubusercontent.com/assets/8228624/9332546/c419b4de-458a-11e5-8c46-01d4caf5ae17.png">

**Comment by FWAJL** [comment]
@gsouvik Taking this since you're on another very high priority issue.

**Comment by gsouvik** [comment]
@FWAJL @bsaiken 
Ok, I was about to ask if I should switch. Thank you.

**Comment by FWAJL** [comment]
@bsaiken @gsouvik 

It is working locally for me so it might not be a big thing.

**Comment by FWAJL** [comment]
@bsaiken @gsouvik 

Found the problem:
![screen shot 2015-08-18 at 17 42 48](https://cloud.githubusercontent.com/assets/7524388/9334769/ae1b56c4-45d0-11e5-8312-208ddbf543ba.png)

However, when I look at the sql script from Jul-24, the column `field_analyte_location_result` should accept null by default but the live server doesn't... @bsaiken : did you change it yourself?

Anyway, I will put this fix for now:
```
$data = array(
              'task_id' => $task_id, 
              'location_id' => $location_id, 
              'field_analyte_id' => $analyte_id,
              'field_analyte_location_result' => "Not sampled");
```

@bsaiken : please validate this solution suits you. Thank you.

**Comment by bsaiken** [comment]
@WebDevJL 
I was working locally and I changed the database so that `field_analyte_location_result` was not null (and therefore did not have the "null" text entered by default. However, I may have accidentally changed the HurrayHost database.  

I need you to push this to the live server and provide an updated script for `field_analyte_location`.

**Comment by FWAJL** [comment]
@bsaiken ok for the possible update but what do we do? Your comment doesn't make what ***this*** is... Sorry.

1. leave the database as it is on live server so field_analyte_location_result requires a value and update the local databases of everybody via an update script? In that case, we need to set a default value for field_analyte_location_result, e.g. in TaskFieldMatrixHelper class, we add: 
```
$data = array(
              'task_id' => $task_id, 
              'location_id' => $location_id, 
              'field_analyte_id' => $analyte_id,
              ***'field_analyte_location_result' => "Not sampled"***);
```

2. or do we revert the live database to allow null in field_analyte_location_result column?

Thank you for the clarification.

**Comment by bsaiken** [comment]
@WebDevJL 
I do not want to see the word "null" as default text in each field.  The text box should just be blank, unless the FT has entered a value.  How that is accomplished is up to you.
