### ISSUE TITLE
Add redirect to the "Exit" button - url = `/mobile/loc_list`

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1243]
This is from the data collection popup.

<img width="1440" alt="screen shot 2015-08-19 at 9 07 42 am" src="https://cloud.githubusercontent.com/assets/8228624/9358478/ecddffe8-4651-11e5-9330-e57ffb229590.png">

**Comment by gsouvik** [comment]
@bsaiken 
Redirect added to the "Exit" button.

**Comment by FWAJL** [comment]
@bsaiken @gsouvik This is not done since Souvik is going to commit the proper fix. Reopening to then release when Souvik is done.

**Comment by FWAJL** [comment]
@gsouvik assign to me when you are done. Thank you.

**Comment by gsouvik** [comment]
@FWAJL @bsaiken 
Done.
