### ISSUE TITLE
Enable contextual menu for Task Locations at `/task/locations`

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1244]

**Comment by gsouvik** [comment]
@bsaiken What would be the menu options?

**Comment by bsaiken** [comment]
@gsouvik 
Edit
We only edit from the contextual menus.  We need to be in edit mode to delete.

**Comment by gsouvik** [comment]
@bsaiken 
I've added the contextual menu with option "Edit" to both the lists on `/task/locations`. However I haven't coded the actual edit functionality as I was unsure if that was part of this issue as well. Let me know if it was and I shall code it.

**Comment by bsaiken** [comment]
@gsouvik 
Yes, add the link.  It should be a small thing since the function is already coded.

**Comment by gsouvik** [comment]
@bsaiken 
Clicking on edit the user is now taken to the location edit form:
`location/showForm?mode=edit&location_id=xyz`

I noticed one issue on that screen, the address field is not getting updated. Though not directly relevant to this issue, I just thought of bringing this to your notice.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
I see what you mean.  I found several bugs - made new Issues.

**Comment by bsaiken** [comment]
@gsouvik 
I just tried this.  I edited the Location description and in automatically inserted the values 0.000 and 0.000 for the `location.lat` and `location.long` fields.  This is incorrect, 0,0 are real coordinates and they are most certainly wrong.

**Comment by FWAJL** [comment]
@bsaiken are you creating a new issue for that bug since you closed this issue at the moment?

**Comment by bsaiken** [comment]
@gsouvik 
I just added a new location from the left menu and the coordinates are 0.000, 0.000, so the problems is systemic.

**Comment by gsouvik** [comment]
@bsaiken 
Yes, this is happening due to default value of the column or there could be a code setting default value. I see the messages for me, but the task is assigned to @damirius. Let me know if you actually wanted me to investigate and fix.

**Comment by bsaiken** [comment]
@gsouvik @damirius 
Sorry Souvik, I meant the message for Damir, since he was the one working with coordinates.

**Comment by damirius** [comment]
@bsaiken @WebDevJL 

Address should be shown properly now in the form. Also empty coordinates should be stored in the DB as NULLs instead which should fix problems when adding or editing.
