### ISSUE TITLE
Duplication check being used in edit mode for Service Providers

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1247]
We are checking for a duplicate name in edit more for Service Providers.  Since we are editing, the Service Provider name will obviously be a "duplicate".  As-is, this function prevents editing.  

Check this for all instances where duplicates are checked (in edit mode).

<img width="1440" alt="screen shot 2015-08-21 at 9 41 28 am" src="https://cloud.githubusercontent.com/assets/8228624/9411018/290b9794-47e9-11e5-9cfc-ecf7f8a6e96a.png">

**Comment by WebDevJL** [comment]
@bsaiken 

So you want to simply check if we implement the duplicate check when editing a project, location, field parameter, etc? Is that correct?

Thank you.

**Comment by gsouvik** [comment]
@bsaiken 
Duplicate check with self restricted while editing service provider.

**Comment by bsaiken** [comment]
@gsouvik 
that appears to work.
