### ISSUE TITLE
Bug adding new Project

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1248]
If a new Project is added, but there is no Facility name, nothing happens. 
There is supposed to be a popup here alerting the user that a Facility name is required.

**Comment by WebDevJL** [comment]
@bsaiken 

We never added a popup alerting the facility name is required except when using the Toastr notification, which you removed in b684460.

Do you want a alert popup similar to the unique project name check?

Thank you.

**Comment by bsaiken** [comment]
@WebDevJL 
Please don't just override my Issue assignments.

**Comment by gsouvik** [comment]
@bsaiken 
Just confirming, currently it shows a popup alert if there is no project name, facility address and client email address. All of these messages appear collectively in a single popup alert. So, this requirement is to include the facility name as well in the mandatory fields list so that the popup alert may show up if the facility name is empty?

**Comment by bsaiken** [comment]
@gsouvik 
The Facility name is a requirement.  Try adding a Project without a Facility name.
Since it is required, we need it to be included in the list of items that are required, so the the user knows what happened.

**Comment by gsouvik** [comment]
@bsaiken 
Facility name is now included in validation and notify user using Popup alert if no data is entered.

However on my branch I just noticed the actual project add feature is not working. It throws the following error:
`Undefined variable: userId`
On ClientController.php file. This is not related to the validation code change, but I just wanted to bring this to your notice.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
I think the error has to do with the auto-creation of a client id and password.  We set this feature up, but it is not needed at this time.  Thanks for pointing that out, though.

**Comment by WebDevJL** [comment]
@bsaiken @gsouvik 

This is fixed by adding a config value to enable the user creation on client creation.
