### ISSUE TITLE
`/task/checklist` is broken on the feature branches, but works on the live site.  See if you can determine why.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1249]

**Comment by gsouvik** [comment]
@bsaiken 
On my local I can't even find the menu from where I may access the page and investigate what the issue might be. Accessing it directly shows php variable not found. Could you please give me a test login on live so that I may login and see the page.  
Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
I believe we determined that my local database was not up to date.  It is working now on the dev branch, so false alarm I think.
