### ISSUE TITLE
Test all the issues to be release on dev branch

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkManager#1255]
@damirius @gsouvik @bsaiken 

The coming release is consequent. I had some troubles merging all the updates from the feature branches to dev branch.

So in order to release a working version, could you test your developments on dev and notify me about any merge errors that could have happened ?
The items to check are those: https://github.com/FWAJL/FieldWorkManager/labels/version%3A1.7.14

Please provide the code to fix if needed here in this issue by specifying the file(s) and related lines to modify/add. This is to avoid conflicts as we will work on the same branch. I will on my end do a special code review on the dev branch.

Thank you.

**Comment by bsaiken** [comment]
@damirius @gsouvik 
This is obviously my territory (to test) and I was able to make the necessary fixes.

Issue                  Working on Dev?
#1244                      Y
#1243                      Y
#1242                      Y - one of the commits was omitted.  I fixed it with https://github.com/FWAJL/FieldWorkManager/commit/98b4c1f477ce014a9c3f59abb6b1a591842a0bc6
#1207                       Y
#1187                       Y
#1171                       Y
#1170                       Y
#1168                       Y
#1153                       Y - I'm not sure how to check this until it is released.
#1142                       Y

**Comment by FWAJL** [comment]
@bsaiken thank you.

#1242 was not omitted but rather @damirius and @gsouvik made updates to it (a lot!) and a merge fix, I probably didn't choose the right line. Thank you rectifying it.
