### ISSUE TITLE
Build the browser history correctly

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkManager#395]
Because of all the AJAX requests and the navigation logic, the browser history is messed up, e.g. when you click the back button, it doesn't go where you were last.

Therefore, we need to build the Browser history as we navigate and make ajax request.

This is a major issue.

**Comment by bsaiken** [comment]
This may be something to farm out to a freelancer

**Comment by FWAJL** [comment]
This is a core task. Let me think about it.

--
Jérémie Litzler

**Comment by FWAJL** [comment]
@bsaiken 

Ok to farm out the dev for this. I don't have time to think about it. It is very specific task.

Basically, we need someone who is experience in dealing with browser history and building a good history with a web application using PHP and JavaScript heavily.

**Comment by FWAJL** [comment]
Possible solution: http://html5demos.com/history

**Comment by FWAJL** [comment]
@bsaiken 

I have been thinking about this and if you show the tool to your future clients, you can't tell them not to type single quotes.

We may need to re-prioritize this by the end of May.
