### ISSUE TITLE
Check and clear the user session

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkManager#758]
TODOs:

1. Hash the session id store in `user` table
2. Implement a session timeout
3. Clear session cleanly

See issue #745 for some more details.

**Comment by bsaiken** [comment]
@FWAJL 
As I said in my comment to Issue #250, I do NOT want to prevent multiple log-in of the same user.  Item 2 must be removed from this Issue.

**Comment by FWAJL** [comment]
@bsaiken 

Done.

**Comment by bsaiken** [comment]
@FWAJL 
Can we close this Issue?

**Comment by FWAJL** [comment]
@bsaiken 

No, it is not done. Let's keep it for later.
