### ISSUE TITLE
Email new FT with their login

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#813]
Send an email to the newly added FT to let them know they can log into the site, and that their temporary username and password is their email address.

**Comment by FWAJL** [comment]
@bsaiken 

#877 is a prerequisite.

**Comment by bsaiken** [comment]
@damirius 
Your list is getting thin again.  Do you think we can tackle this before the end of the week?

**Comment by damirius** [comment]
@bsaiken

I guess we have emailer class implemented, but we do lack some stuff like email db backups and email storage for resending them.
I don't know if this is needed for this Issue.

**Comment by bsaiken** [comment]
@damirius 
We don't have time for everything.  What I am referring to specifically here is adding a new FT user.  Instead of automatically creating a FT user, we send them an email inviting them to the website.  This requires the FT to respond before they are added as a user.  It is a security step.  If the site moves forward, a high level of security will be needed.
