### ISSUE TITLE
Modify required fields to create a new PM user at /user/showForm

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#875]
The only required fields should be Login and password.

**Comment by FWAJL** [comment]
@bsaiken 

This is already done in the Admin UI. Do you see it? Log in as admintest and browser Users > Add and select pm_id role.

**Comment by bsaiken** [comment]
@FWAJL 
You must not have read my comment.  Right now, all fields are required.  I only want the login and password to be required.

**Comment by FWAJL** [comment]
@bsaiken 
Understood.
