### ISSUE TITLE
Changes to Mapping - Active Task view

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#974]
Take a look at the map legend.  Use the map legend view module: `popup_maplegend_active_task.php`.

The color of the marker depends on the work being performed.  All Task Locations start out red (not started).  So the color of the marker will be:
 * Red - not started (when the Task is first activated).
 * Yellow - in process.  This will be the condition after the first time the Field Technician does any work on the Task at this Location.  
 * Green - finished.  This will be the condition after all location-forms have been completed and/or, if the Location did not have coordinates when the Task started, the Location coordinates have been added.

Since we are working on the Mobile UI right now, there won't be any Tasks in process or completed.  However, you could still add a column to the `task_location` table: `task_location_status`.  Then we can assign the status like so: 0 = not started; 1 = in process; 2 = finished.  For testing, we can manually populate the table values.  This is how I think it will work - if there is a better way let me know.

**Comment by bsaiken** [comment]
@damirius 
I see your Issue list is getting light.  Please take a look at my description for the `Mobile Site Integration` Milestone.  https://github.com/FWAJL/FieldWorkAssistantMVC/milestones/21/edit  
It's an email I sent to Jeremie about how the Mobile UI will get done, and you are mentioned several times, so you can see what's coming up.

**Comment by bsaiken** [comment]
@damirius 
So, the info window for the active task view is the same as the Task View (see Issue #971), EXCEPT that we must remove the link "Remove from Task" or "Add to Task" (depending on if it is a Task location or Project Location).  Once it is an active Task it is "static", we can assign or unassigned Task Locations any more.

You could assign this over to Souvik if you want.

**Comment by damirius** [comment]
@bsaiken

Already working on it. Thanks for those additional details, appreciate it.

**Comment by damirius** [comment]
@bsaiken

One thing to think about. We currently show both active and inactive tasks, or rather should I say started and not yet started tasks in Map->Task Locations, it doesn't make a difference. If someone goes to Tasks->List All, chooses task from the list and clicks on 'check status' and then goes there to the map (activetask/map) he will see the map with color coded markers and without ability to remove/add locations from that task. But if he goes to Map->Task Locations he will see the map for that same task, just without color coding and WITH ability to add/remove locations from the task. 
How do we prevent this? I can add check there too, to see if selected task is set to active and hide those add/remove buttons in the infowindows like we do on the activetask map.
Tell me what do you think

**Comment by damirius** [comment]
@bsaiken

Color coding is done for the active task maps, along with infowindows. 
Before doing anything please update the DB, you can find sql file in the usual directory named 2015-05-19.sql
Since I had to add task_location_status field like you suggested.
Everything is on feature_damir branch.

**Comment by bsaiken** [comment]
@damirius 
Even though it's the same Task, the behavior for Active Tasks and Inactive Tasks is different.  In inactive mode, we are constructing, or modifying the Task.  So, it is OK to assign and un-assign Locations.  Once the Task is active, the we will not be able to assign or un-assign Locations.  So if we just get rid of the link in the info window, even thought the js function exists, there would be no way to access it.  

We do need to be able to move markers in both active and inactive mode.  One of the possible purposes of the Task is to correctly identify the coordinates, so obviously we need to be able to do that in Active mode as well.

We can apply the color coding to the inactive task mode as well using the `task_location_status`.  The default, while constructing the task, is `task_location_status=0`, so they'd all appear red until we activated the Task and did some work.

**Comment by damirius** [comment]
@bsaiken

I understand that. I wanted to say that old map Map->Task locations (map/taskLocations), is still showing remove/add to task links since everything mentioned here is done for the activetask/map which can be accessed only through 'check status' page which is available for the active tasks anyway. So that said PM, can still access old map and remove/add locations to the task.
I understand that old task locations map (map/taskLocations) should be used while task isn't yet set to active, but currently we aren't stopping the user to access it even when it is set to active.

**Comment by bsaiken** [comment]
@damirius 
Little things like this I can fix.  Since we are in a time crunch, don't be afraid to assign me more trivial tasks, especially if they are trivial and time consuming.
