### ISSUE TITLE
Prevent duplicate forms on Task Activation

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#984]
@gsouvik @FWAJL 

Jeremie, I want your opinion on my proposed approach.

Activating a Task copies the master or user forms.  If the task is deactivated, then reactivated, duplicate forms are created.  This will happen every time the Task is activated and re-activated.  

We need to add code so that this Task Activation function will only happen once, no matter how many times the Task is activated.  This could apply to other functions in the future, so make it a generic fix.

I don't know the best way to do this, but I thought of one option.  Add a column to the `task` table: `task_activated`.  The default value for this could be `0`, then once the Task is activated the first time, we check to make sure `task.task_activated===0`.  If this is the case, then copy the forms (and perform other functions) and set `task.task_activated=1`.

**Comment by FWAJL** [comment]
@bsaiken @gsouvik 

> @bsaiken said:
> This could apply to other functions in the future, so make it a generic fix.

Do you have another use case where we would need this? Please give examples if possible.

Your proposition is a possible solution indeed. So if you deactivate the task, the "activated" flag remains set to 1 so that we only don't create the forms twice?

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 

> @FWAJL said:
> So if you deactivate the task, the "activated" flag remains set to 1 so that we only don't create the forms twice?

This is correct, so let's move forward with this implementation.  Jeremie, please made the database change and give us an update script.  I have not doe a database reset yet, so give me a new database reset script as well.

As far as an example of other use cases, there are several, but I do not think we will get to them by the end of May.  For example, when a Task is activated for the first time, an email will be sent to the Field Technician(s) assigned to the Task.  Another example, I have Mehedee working to pre-populate the pdf forms that are created with the Location name for each form.  Obviously, if the forms only get made once, this action will only be done once.  This example is not as clear cut because the forms must be created in order to pre-populate them, so we could insert the trigger into the code to create the forms.  However, form creation and FT invitations are independent, so both would depend on the `task.task_activated` value.  I made a more comprehensive list of functions that would occur when a task is activated here: https://docs.google.com/document/d/1-fwonCMNcIhRT-4xsO7cnzh5gT74GwfD7c5NQjk4INk/edit?pli=1
Some of the items on the list may be deprecated now, but you can see there are a number of items on the list.  Some will be dependent, some will not.  I think the `task.task_activated` approach would cover all potential cases.

**Comment by FWAJL** [comment]
@bsaiken @gsouvik 

Code committed on devsupport branch for Souvik.

As for the DB reset script, it is unchanged from last time and is here:

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
When tasks are activated, the column `task_activated` is getting marked with 1 and it stays there forever. Depending on that column's data, if it is not 1, we are executing the location specific PDF generation process.

In other words location specific PDFs are only generated when the task is activated first time. Any subsequent activation/deactivation doesn't initiate any form copy process.

**Comment by bsaiken** [comment]
@gsouvik 
Try to Add a new Task and see if you have a bug.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
The Add task feature had a bug. This was due to the fact, while adding the "dataPost" variable was not having `task_activated` column in it explicitly defined. Strange, because on the database end a default is set. I've kept a checking and now setting it to 0 if nothing is found, and that solved the issue.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
That fixes the Add task feature, but I am still seeing some major bugs.  The copy forms function is not working.  It is working on the live site, but even the DEV branch is corrupted.  Can you try promoting a Task to Active and show me that you are getting the correct forms copied?

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
Ok, let me take up one example from my local tasks - "Monitoring"

Step 1: 
The task is inactive

![1](https://cloud.githubusercontent.com/assets/2292482/7683513/44c32a2e-fd9d-11e4-99eb-9e76350b32ec.png)

Step 2:
Editing it shows it's forms, total 3 of those, one user form and couple of master form:

![2](https://cloud.githubusercontent.com/assets/2292482/7683575/9c244ed8-fd9d-11e4-8773-33d0f98456d2.png)

Step 3:
Let's see it's locations, there are two of them, so when the forms are copied there should be 6 total forms:

![3](https://cloud.githubusercontent.com/assets/2292482/7683598/cbbb9598-fd9d-11e4-819c-fe834c10c486.png)

Step 4:
Promoting to active task
![4](https://cloud.githubusercontent.com/assets/2292482/7683690/53bf1578-fd9e-11e4-9570-efa73d8ba105.png)

Step 5:
Promoted successfully:
![5](https://cloud.githubusercontent.com/assets/2292482/7683713/7cf41fb0-fd9e-11e4-8f77-662f1602ae21.png)

Step 6:
Let's look at the disc, the 6 forms are created

![6](https://cloud.githubusercontent.com/assets/2292482/7683738/a2f9e76c-fd9e-11e4-8e49-8145ca13bbaf.png)

Step 7:
Verifying in the active task forms tab, the forms are available there too:

![7](https://cloud.githubusercontent.com/assets/2292482/7683786/fa915334-fd9e-11e4-9da7-d62d553b1fb4.png)

The form names are matching with the location names and the original source forms. So the form copy function works good on my local. Let me know if you see other bugs and wish me to specifically test them.

**Comment by bsaiken** [comment]
@gsouvik 
This is probably a database Issue then.  Let me look into it.

**Comment by bsaiken** [comment]
@gsouvik 
I think it is the database.  Will you please send me the script for the database you are using.

**Comment by gsouvik** [comment]
@bsaiken 
Have you applied this script to your database?
https://github.com/FWAJL/FieldWorkAssistantMVC/blob/feature_devsupport/Database/Scripts/Updates/2015-05-13.sql

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
I am having no luck at all.  Can you give me the script for your entire database?

**Comment by gsouvik** [comment]
@bsaiken 
Sent my local db through Elance.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 

OK - this is working.  It isn't just the database.  There is a database mismatch between uploaded (master) files, which reside in a folder, and the `document` database table.  Every time, I need to start from scratch to test.

**Comment by bsaiken** [comment]
@FWAJL @damirius 
Forms are not being generated.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

This should be fixed on feature_damir branch.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
This has been happening from time to time, so I am convinced there is some kind of bug.
Notice how there is a new location-form with the title "Test Photo".  
![screen shot 2015-05-31 at 6 45 40 am](https://cloud.githubusercontent.com/assets/8228624/7902123/3ef4650e-0761-11e5-81fc-ef78bd7f58ee.png)

"Test Photo" exists, but it is associated with a Project Location (*not* a Task Location) MW-112B2. 
![screen shot 2015-05-31 at 6 49 20 am](https://cloud.githubusercontent.com/assets/8228624/7902130/6302d3e0-0761-11e5-8059-040a21e1324b.png)

**Comment by damirius** [comment]
@bsaiken @FWAJL 

As far as I see that Test Photo isn't associated with anything if I'm not missing something. Form should be named `FORM-NAME_TASK-LOCATION-NAME`.
When task is activated, copies of each form (both user and master) should be created for each task location. So if we have 2 forms assigned to the task and 3 locations we would have 6 form copies, 2 forms for each location right?
I've tried to check if I can get something else than that few times. Here is the full video:
https://drive.google.com/file/d/0B7Laiv0PjSvDN0VMRDdfemdYMlU/view?usp=sharing

I'll try to see if I can recreate this bug by trying something else

**Comment by bsaiken** [comment]
@damirius @FWAJL 
If you can't see the reason in the code, I will try to re-create the specific and reproducible condition.  
However, today (Sunday) I am completely booked, so there may not be time.
